import type { IntegrationRecipe } from "@/lib/studio/integration-recipes";

export const integrationRecipes: IntegrationRecipe[] = [
  {
    slug: "whatsapp",
    target: "whatsapp",
    name: "WhatsApp CTA",
    plainMeaning: "Botones que abren una conversación con mensaje listo.",
    whenToUse: "Cuando el cliente quiere recibir consultas rápidas sin formulario.",
    whatWeNeed: ["Número con código de país", "Mensaje inicial", "Horarios o zona si aplica"],
    implementationSteps: [
      "Crear link wa.me con mensaje codificado",
      "Poner CTA en hero",
      "Repetir CTA en secciones clave y footer",
      "Usar texto de botón claro: Consultar por WhatsApp",
    ],
    qaChecklist: ["Abre WhatsApp Web/Desktop", "Abre en celular", "Mensaje aparece precargado", "Número correcto"],
    boundaries: ["No prometemos responder mensajes por el cliente", "No usamos números personales sin aprobación"],
  },
  {
    slug: "forms",
    target: "forms",
    name: "Formulario de contacto",
    plainMeaning: "Formulario simple para captar nombre, email, teléfono y consulta.",
    whenToUse: "Cuando el cliente necesita leads más ordenados que WhatsApp.",
    whatWeNeed: ["Campos requeridos", "Email destino o herramienta", "Mensaje de éxito", "Política de privacidad si aplica"],
    implementationSteps: [
      "Definir campos mínimos",
      "Conectar destino del formulario",
      "Agregar estado de éxito/error",
      "Guardar evento para analytics si aplica",
    ],
    qaChecklist: ["Envío funciona", "Llegan los datos", "Errores se entienden", "No pide campos innecesarios"],
    boundaries: ["No almacenar datos sensibles sin necesidad", "No pedir datos médicos/legales sensibles sin flujo adecuado"],
  },
  {
    slug: "tiendanube",
    target: "tiendanube",
    name: "Tiendanube como checkout",
    plainMeaning: "Nuestra web es la vidriera; Tiendanube maneja carrito, pagos, stock y pedidos.",
    whenToUse: "Cuando el cliente vende productos y no conviene hacer ecommerce custom.",
    whatWeNeed: ["URL de la tienda", "Links de productos/categorías", "Productos destacados", "Fotos y textos de marca"],
    implementationSteps: [
      "Crear secciones de marca y productos destacados",
      "Usar botones hacia productos/categorías de Tiendanube",
      "Mantener checkout dentro de Tiendanube",
      "Probar el camino hasta antes de pagar",
    ],
    qaChecklist: ["Links correctos", "Productos activos", "Checkout carga", "Mobile funciona", "No hay productos agotados destacados"],
    boundaries: ["No tocamos pagos/stock sin aprobación", "No hacemos checkout custom barato", "El cliente maneja datos fiscales y cobros"],
  },
  {
    slug: "mercadopago",
    target: "mercadopago",
    name: "Link de MercadoPago",
    plainMeaning: "Botón de compra simple que manda a un link de pago.",
    whenToUse: "Cuando hay pocos productos, preventas, reservas o pagos simples.",
    whatWeNeed: ["Link de pago", "Precio", "Qué incluye", "Condiciones de compra"],
    implementationSteps: ["Crear sección de oferta", "Poner CTA de compra", "Explicar qué pasa después de pagar"],
    qaChecklist: ["Link abre", "Monto correcto", "Producto correcto", "CTA no confunde"],
    boundaries: ["No gestionamos reclamos de pago", "No tocamos cuentas bancarias del cliente"],
  },
  {
    slug: "vercel-domain",
    target: "domain",
    name: "Vercel + dominio",
    plainMeaning: "Publicar la web y conectarla al dominio del cliente.",
    whenToUse: "Siempre que una landing o vidriera pase a producción.",
    whatWeNeed: ["Repo GitHub", "Cuenta/proyecto Vercel", "Dominio", "Acceso DNS o instrucciones para el cliente"],
    implementationSteps: ["Conectar repo a Vercel", "Configurar variables si hay", "Agregar dominio", "Configurar DNS", "Esperar SSL"],
    qaChecklist: ["Preview funciona", "Dominio responde", "SSL activo", "www/no-www definido", "Build production OK"],
    boundaries: ["No comprar dominios con medios de pago propios", "No tocar DNS sin aprobación"],
  },
  {
    slug: "analytics",
    target: "analytics",
    name: "Analytics básico",
    plainMeaning: "Medición mínima para saber si la web recibe visitas y clicks.",
    whenToUse: "Cuando el cliente quiere medir tráfico, campañas o conversiones.",
    whatWeNeed: ["Herramienta elegida", "ID de medición", "Eventos importantes"],
    implementationSteps: ["Instalar script", "Medir pageviews", "Medir clicks importantes", "Probar en producción"],
    qaChecklist: ["Script carga", "Pageview aparece", "CTA trackeado", "No rompe performance"],
    boundaries: ["No prometer resultados de marketing solo por instalar analytics", "No usar cuentas personales del cliente sin permiso"],
  },
];
