import type { ProductionStep } from "@/lib/studio/production-pipeline";

export const productionPipeline: ProductionStep[] = [
  {
    id: "intake",
    order: 1,
    title: "Cargar cliente / intake",
    plainMeaning: "Ordenamos qué vende el cliente, para quién, qué objetivo tiene y qué referencias le gustan.",
    outcome: "Ficha clara para no arrancar desde el caos.",
    route: "/clients",
    uses: ["Client Intake", "Referencias", "Objetivo comercial"],
    status: "ready",
  },
  {
    id: "offer",
    order: 2,
    title: "Elegir oferta vendible",
    plainMeaning: "Decidimos si conviene vender Landing Premium o Ecommerce + Tiendanube.",
    outcome: "Alcance claro y menos riesgo de prometer de más.",
    route: "/",
    uses: ["Ofertas", "Límites", "Tipo de cliente"],
    status: "ready",
  },
  {
    id: "template",
    order: 3,
    title: "Elegir plantilla base",
    plainMeaning: "No empezamos de cero: elegimos el molde más cercano.",
    outcome: "Una base reusable para acelerar la demo.",
    route: "/templates",
    uses: ["Plantillas", "Readiness", "Dirección visual"],
    status: "ready",
  },
  {
    id: "niche-demo",
    order: 4,
    title: "Crear demo de nicho",
    plainMeaning: "Convertimos la plantilla general en una demo específica para ese rubro.",
    outcome: "Demo visible para mostrar o vender.",
    route: "/demos/dark-premium",
    uses: ["Niche Demo", "Template base", "Copy específico"],
    status: "not-started",
  },
  {
    id: "integrations",
    order: 5,
    title: "Conectar integraciones",
    plainMeaning: "Agregamos WhatsApp, formulario, Tiendanube, MercadoPago, Vercel o analytics según corresponda.",
    outcome: "La web no solo se ve bien: funciona comercialmente.",
    route: "/integrations",
    uses: ["Integration Recipes", "QA de links", "Límites"],
    status: "ready",
  },
  {
    id: "qa",
    order: 6,
    title: "Pasar Launch Checklist",
    plainMeaning: "Revisamos si la web está lista para entregar sin vergüenza.",
    outcome: "Control de calidad antes de publicar.",
    route: "/checklist",
    uses: ["Checklist", "Mobile", "SEO", "Build"],
    status: "ready",
  },
  {
    id: "deploy",
    order: 7,
    title: "Deploy y entrega",
    plainMeaning: "Publicamos, conectamos dominio si hace falta y dejamos notas de entrega.",
    outcome: "Web lista para cliente o portfolio.",
    route: "/system",
    uses: ["Vercel", "Dominio", "Handoff"],
    status: "not-started",
  },
];
